---
- hosts: srlinux
  tasks:
   - name: scp
     copy:
        src: static-vxlan-agent-0.1.0.x86_64.rpm
        dest: /tmp/static-vxlan-agent-0.1.0.x86_64.rpm
        mode: 0755
   - name: install
     shell: sudo rpm -ivh  /tmp/static-vxlan-agent-0.1.0.x86_64.rpm
   - name: reload the appmgr
     shell: sr_cli tools system app-management application app_mgr reload
